### ISSUE TITLE
How to wrap the repo up as a python package

### ISSUE THREAD

**Issue by wmmxk** [MTB90/cuda_floyd-warshall#2]
This is not an issue but an extension. I was trying to add a setup.py file in the repo to convert it to a python package. The hard part is how to run make all in the setup.py file. The setup.py I tried now is as follows, but it does not work. Do you have expertise in this regard?

import subprocess
from setuptools import Command
from setuptools import setup

class CustomInstall(Command):
    user_options = []
    def initialize_options(self):
        pass
    def finalize_options(self):
        pass
    def run(self):
        subprocess.call(
            ['make --directory=/mnt/tmp/cuda-floyd_warshall  all']
        )
setup(
    name='apsp',
    version='0.1',
    cmdclass={'customcommand': CustomInstall}
)

**Comment by MTB90** [comment]
Unfortunately not. Maybe look on how numpy  do this. Also this can helps
https://docs.python.org/3/extending/extending.html
https://www.boost.org/doc/libs/1_49_0/libs/python/doc/

**Comment by MTB90** [comment]
As I understood you want use this code in Python?
Another why can be rewrite this algorithm to use numba + cuda: https://numba.pydata.org/numba-doc/dev/cuda/examples.html but probably some performance will be lost

**Comment by wmmxk** [comment]
I really appreciate your reply. Yes, for now I can download and compile your code and use it in Python. You already connected the cuda code with Python. That is nice. I will look into the numba+cuda version. Thanks.

**Comment by MTB90** [comment]
This connection cuda code and Python I written only for simple unit tests. For sure this is not optimal solution.

**Comment by wmmxk** [comment]
It turns out there are not materials online about connecting cuda code to python. There is one here: http://alanpryorjr.com/2017-07-12-pipcudemo/ . I am looking into it.

**Comment by MTB90** [comment]
Probably in this weekend I will check how this will work using only Python with numba.
I am quite curious about performance using numba.

**Comment by MTB90** [comment]
Close
